/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	parochiv1 "github.com/parochi/greeting-client/pkg/apis/parochi/v1"
	versioned "github.com/parochi/greeting-client/pkg/client/clientset/versioned"
	internalinterfaces "github.com/parochi/greeting-client/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/parochi/greeting-client/pkg/client/listers/parochi/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GreetingInformer provides access to a shared informer and lister for
// Greetings.
type GreetingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.GreetingLister
}

type greetingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGreetingInformer constructs a new informer for Greeting type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGreetingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGreetingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGreetingInformer constructs a new informer for Greeting type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGreetingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ParochiV1().Greetings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ParochiV1().Greetings(namespace).Watch(context.TODO(), options)
			},
		},
		&parochiv1.Greeting{},
		resyncPeriod,
		indexers,
	)
}

func (f *greetingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGreetingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *greetingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&parochiv1.Greeting{}, f.defaultInformer)
}

func (f *greetingInformer) Lister() v1.GreetingLister {
	return v1.NewGreetingLister(f.Informer().GetIndexer())
}
