/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	parochiv1 "github.com/parochi/greeting-client/pkg/apis/parochi/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGreetings implements GreetingInterface
type FakeGreetings struct {
	Fake *FakeParochiV1
	ns   string
}

var greetingsResource = schema.GroupVersionResource{Group: "parochi.com", Version: "v1", Resource: "greetings"}

var greetingsKind = schema.GroupVersionKind{Group: "parochi.com", Version: "v1", Kind: "Greeting"}

// Get takes name of the greeting, and returns the corresponding greeting object, and an error if there is any.
func (c *FakeGreetings) Get(ctx context.Context, name string, options v1.GetOptions) (result *parochiv1.Greeting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(greetingsResource, c.ns, name), &parochiv1.Greeting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*parochiv1.Greeting), err
}

// List takes label and field selectors, and returns the list of Greetings that match those selectors.
func (c *FakeGreetings) List(ctx context.Context, opts v1.ListOptions) (result *parochiv1.GreetingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(greetingsResource, greetingsKind, c.ns, opts), &parochiv1.GreetingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &parochiv1.GreetingList{ListMeta: obj.(*parochiv1.GreetingList).ListMeta}
	for _, item := range obj.(*parochiv1.GreetingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested greetings.
func (c *FakeGreetings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(greetingsResource, c.ns, opts))

}

// Create takes the representation of a greeting and creates it.  Returns the server's representation of the greeting, and an error, if there is any.
func (c *FakeGreetings) Create(ctx context.Context, greeting *parochiv1.Greeting, opts v1.CreateOptions) (result *parochiv1.Greeting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(greetingsResource, c.ns, greeting), &parochiv1.Greeting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*parochiv1.Greeting), err
}

// Update takes the representation of a greeting and updates it. Returns the server's representation of the greeting, and an error, if there is any.
func (c *FakeGreetings) Update(ctx context.Context, greeting *parochiv1.Greeting, opts v1.UpdateOptions) (result *parochiv1.Greeting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(greetingsResource, c.ns, greeting), &parochiv1.Greeting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*parochiv1.Greeting), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGreetings) UpdateStatus(ctx context.Context, greeting *parochiv1.Greeting, opts v1.UpdateOptions) (*parochiv1.Greeting, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(greetingsResource, "status", c.ns, greeting), &parochiv1.Greeting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*parochiv1.Greeting), err
}

// Delete takes name of the greeting and deletes it. Returns an error if one occurs.
func (c *FakeGreetings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(greetingsResource, c.ns, name), &parochiv1.Greeting{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGreetings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(greetingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &parochiv1.GreetingList{})
	return err
}

// Patch applies the patch and returns the patched greeting.
func (c *FakeGreetings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *parochiv1.Greeting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(greetingsResource, c.ns, name, pt, data, subresources...), &parochiv1.Greeting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*parochiv1.Greeting), err
}
